name: news_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.3
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  lottie: ^2.0.0
  url_launcher:
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: 2.5.2
  json_serializable: 6.8.0
  build_runner: 2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/
